import os
from snakemake.utils import min_version

min_version("6.4.1")

wildcard_constraints:
    sample="[\da-zA-Z]+"

##### setup report #####
configfile: "config/config.yaml"

##### setup singularity #####


# this container defines the underlying OS for each job when using the workflow
# with --use-conda --use-singularity
container: "docker://condaforge/mambaforge:22.11.1-4"



include: "rules/common.smk"
include: "rules/gloriseq_dataprep.smk"
include: "rules/gloriseq_indexprep.smk"
include: "rules/gloritools.smk"


##### target rules #####


rule all:
    input:
        get_final_output(),