
threads:
  trim_galore: 8
  seqkit_rmdup: 8
  fastx_trimmer: 1

gloritools:
  trim_galore: ' -q 20 --stringency 1 -e 0.3 --length 35  '
  fastx_trimmer: ' -Q 33 -f 11 '
  gloritools_run: ' --combine --rvs_fac -c 1 -C 0 -r 0 -p 1.1 -adp 1.1 -s 0 '