samples: config/samples.tsv


threads:
  fastp: 16
  gloritools_build_index: 12

gloritools:
  fastp: ' --dedup --dup_calc_accuracy 5 --cut_tail --cut_tail_mean_quality 20 --umi --umi_loc per_read --umi_len 10 '


reference:
  transcriptome_fa: transcriptome.fa
  gtf: transcript.gtf
  genome_fa: genome.fa
